---

# Test für GITLAB-Operationen

- hosts: servers
  remote_user: vagrant
  sudo: true

  vars:
    deployer_user: workathomeuser
    deployer_user_ssh_key_file: .ssh/id_rsa
    bo_gitlab_api: https://localhost:8443/api/v3/
    bo_gitlab_key_title: automationathome

  vars_files:
    - secrets.yml

  tasks:

    - name: update all packages
      command: yum -y update

#    - name: install httplib2 (für gitlab notwendig)
#      yum: name=python-httplib2 state=latest

    - name: install httplib2 (für uri, Zugriff auf gitlab)
      pip: name=httplib2

    # deploy-user immer löschen, dann neu 
    - name: erzeuge ssh-key
      user: name={{ deployer_user }} generate_ssh_key=yes 

    - name: Assign ssh key to a variable
      shell: cat /home/{{ deployer_user }}/{{ deployer_user_ssh_key_file }}.pub
      register: deployer_user_public_key

    # key immer löschen, immer neuanlegen
    - name: Delete older keys from the Gitlab instance
      uri: >
        url="{{ bo_gitlab_api }}user/keys"
        method=DELETE
        status_code=201
        HEADER_PRIVATE-TOKEN="{{ bo_gitlab_token }}"
        HEADER_Content-Type="application/json"
        body="{\"title\": \"{{ bo_gitlab_key_title }}\"}"

    # ggf. auch so: key immer löschen, immer neuanlegen
    - name: Push the generated ssh key to the Gitlab instance
      uri: >
        url="{{ bo_gitlab_api }}user/keys"
        method=POST
        status_code=201
        HEADER_PRIVATE-TOKEN="{{ bo_gitlab_token }}"
        HEADER_Content-Type="application/json"
        body="{\"title\": \"{{ bo_gitlab_key_title }}\", \"key\": \"{{ deployer_user_public_key.stdout_lines.0 }}\"}"

       
